apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-python
  namespace: default
  labels:
    app: mi-app-python
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app-python
  template:
    metadata:
      labels:
        app: mi-app-python
        version: v1
    spec:
      containers:
      - name: mi-app-python
        image: lchacon74/mi-app-python:sha256:f87cda1ad88b4dcba8e011f3aece747d8911c2cdaa7194709af54a50fe8d596c
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
      restartPolicy: Always
