apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-python
  namespace: default
  labels:
    app: mi-app-python
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app-python
  template:
    metadata:
      labels:
        app: mi-app-python
        version: v1
    spec:
      containers:
      - name: mi-app-python
        image: lchacon74/mi-app-python:sha-13a75a0b9eaa0f83e9f2b542088da7e13d0bbfbf
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
      restartPolicy: Always
